// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var exchangeBulkSplit = ExchangeBulkSplit.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ExchangeBulkSplit
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("exchange")]
        public string Exchange { get; set; }

        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("split")]
        public string Split { get; set; }
    }

    public partial class ExchangeBulkSplit
    {
        public static List<ExchangeBulkSplit> FromJson(string json) => JsonConvert.DeserializeObject<List<ExchangeBulkSplit>>(json, EODHistoricalData.NET.ExchangeBulkSplitConverter.Settings);
    }

    public static class ExchangeBulkSplitSerialize
    {
        public static string ToJson(this List<ExchangeBulkSplit> self) => JsonConvert.SerializeObject(self, EODHistoricalData.NET.ExchangeBulkSplitConverter.Settings);
    }

    internal static class ExchangeBulkSplitConverter
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal },
                new NullConverter(),
            },
            Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            {
                Errors.Add(args.ErrorContext.Error.Message);
                args.ErrorContext.Handled = true;
            },
        };
    }
}
