// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var exchangeBulkDividend = ExchangeBulkDividend.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ExchangeBulkDividend
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("exchange")]
        public string Exchange { get; set; }

        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("dividend")]
        public string Dividend { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("declarationDate")]
        public DateTimeOffset? DeclarationDate { get; set; }

        [JsonProperty("recordDate")]
        public DateTimeOffset? RecordDate { get; set; }

        [JsonProperty("paymentDate")]
        public DateTimeOffset? PaymentDate { get; set; }

        [JsonProperty("period")]
        public string Period { get; set; }

        [JsonProperty("unadjustedValue")]
        public string UnadjustedValue { get; set; }
    }

    public partial class ExchangeBulkDividend
    {
        public static List<ExchangeBulkDividend> FromJson(string json) => JsonConvert.DeserializeObject<List<ExchangeBulkDividend>>(json, EODHistoricalData.NET.ExchangeBulkDividendConverter.Settings);
    }

    public static class ExchangeBulkDividendSerialize
    {
        public static string ToJson(this List<ExchangeBulkDividend> self) => JsonConvert.SerializeObject(self, EODHistoricalData.NET.ExchangeBulkDividendConverter.Settings);
    }

    internal static class ExchangeBulkDividendConverter
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal },
                new NullConverter(),
            },
            Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            {
                Errors.Add(args.ErrorContext.Error.Message);
                args.ErrorContext.Handled = true;
            },
        };
    }
}
