// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var instrument = Instrument.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SearchInstrument
    {
        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("Exchange")]
        public string Exchange { get; set; }

        [JsonProperty("Currency")]
        public string Currency { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }
        
        [JsonProperty("ISIN")]
        public string Isin { get; set; }
        
        [JsonProperty("previousClose")]
        public decimal PreviousClose { get; set; }
        
        [JsonProperty("previousCloseDate")]
        public DateTimeOffset PreviousCloseDate { get; set; }
    }
    
    public partial class SearchInstrument
    {
        public static List<SearchInstrument> FromJson(string json) => JsonConvert.DeserializeObject<List<SearchInstrument>>(json, EODHistoricalData.NET.ConverterInstrument.Settings);
    }

    public static class SerializeSearchInstrument
    {
        public static string ToJson(this List<SearchInstrument> self) => JsonConvert.SerializeObject(self, EODHistoricalData.NET.ConverterInstrument.Settings);
    }

    internal static class ConverterSearchInstrument
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal },
                new NullConverter(),
            },
            Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            {
                Errors.Add(args.ErrorContext.Error.Message);
                args.ErrorContext.Handled = true;
            },
        };
    }
}
